### ISSUE TITLE
Suggestion: Recognize structured MIME type suffixes

### ISSUE THREAD

**Issue by IS4Code** [cgutteridge/uri4uri#2]
At the moment, URIs like `<http://uri4uri.net/mime/image/svg+xml>` with the structured suffix `+xml` do not get treated in any special way. However, it would be quite useful to link to `<http://uri4uri.net/mime/application/xml>` from it via some property (`basedOn` or something). This way, one could easily reach a possibly supported MIME type when an unknown one is encountered, without having to parse the notation.

The IANA-managed registry for structured suffixes can be found [here](https://www.iana.org/assignments/media-type-structured-suffix/media-type-structured-suffix.xhtml). Unfortunately I don't think there is a standard way to retrieve the "base" type from the suffix, but it seems just stripping off everything after `+` and appending it to `application/` would work, at least I wasn't able to find any suffix that would be named differently (if registered at all).

**Comment by cgutteridge** [comment]
Hi, I've not thought about this site in years! It was originally a April 1st gag, but had some value for linked data too. However resolvable linked data is doomed because of the value proposition. The people who gain value from something like this are not the ones who pay for it, so these things don't last unless someone backs them. Any ideas of what to do with this welcome, but it's not really relevant to any of my work or current hobby interests...

**Comment by IS4Code** [comment]
I understand. Still, while this started as a joke, it is still especially useful to me as it provides identifiers for MIME types and path suffixes and I was not able to find any alternative other than creating my own. And you can always place a Donate button there to make at least a little profit out of it.
